### PR TITLE
Patch log4j dependency

### PR DESCRIPTION
**Pull request by thomasyu888**

### CODE REVIEW

**Review by brucehoff — APPROVED** [review]

**Comment by thomasyu888** [comment]
@brucehoff Any idea why the test is failing?

**Comment by brucehoff** [comment]
> @brucehoff Any idea why the test is failing?

Yes, you can see the failure in Travis:

```
[ERROR] /home/travis/build/Sage-Bionetworks/SynapseWorkflowOrchestrator/src/main/java/org/sagebionetworks/WorkflowAdmin.java:[23,44] cannot find symbol
  symbol:   class EvaluationStatus
  location: package org.sagebionetworks.evaluation.model
```

This compilation failure was caused by your upgrade to a new version of Synapse that omits the referenced Java class.  EvaluationStatus is likely no longer used.  The fix is probably a simple matter of updating the imports to eliminate the reference to this class.

**Comment by thomasyu888** [comment]
Thanks @brucehoff. I meant to ask for advice on how to fix this issue.  let me give it a shot.

**Comment by brucehoff** [comment]
> Thanks @brucehoff. I meant to ask for advice on how to fix this issue. let me give it a shot.

Sure.  Did my advice (two lines to delete from the specified file) do the trick?

**Comment by thomasyu888** [comment]
@brucehoff there is a new issue:

```
  testGetRepoSuffixFromImage(org.sagebionetworks.SubmissionUtilsTest): Invalid repository name: ubuntu
```

**Comment by brucehoff** [comment]
> @brucehoff yes it did, but there is a new issue now.
> 
> ```
>   testGetRepoSuffixFromImage(org.sagebionetworks.SubmissionUtilsTest): Invalid repository name: ubuntu
> ```

As far as I can tell, then Synapse utility, `DockerNameUtil.getRegistryHost(repoWithoutDigest)` previously returned `null` for `ubuntu` but now throws the exception you see.  You can make the test pass (for now) by replacing `ubuntu` with `ubuntu/something` (i.e. two or more strings with a slash), but we should also fix the Synapse utility.

**Comment by thomasyu888** [comment]
Thanks @brucehoff.  I commented the test out for now. Going to merge

**Pull request merged**
